version: '3.8'

services:
  # Backend service
  backend:
    image: ghcr.io/pterko/tg-chat-webapp-protection-bot:latest # specify your backend image name and tag
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - WEB_APP_URL=YOUR_WEB_APP_URL
      - WEB_APP_TG_URI=YOUR_WEB_APP_TG_URI
      - MONGO_URI=YOUR_EXTERNAL_MONGO_URI
      - RECAPTCHA_SECRET=YOUR_RECAPTCHA_SECRET
    ports:
      - "12000:12000"

  # Watchtower service to auto-update containers
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 backend # This will check for updates every 30 seconds just for the 'backend' service

